/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: src/grpc/proto/test.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./..\\..\\..\\google\\protobuf\\struct";
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "@grpc/grpc-js";
export namespace test {
    export class Int extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            val?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("val" in data && data.val != undefined) {
                    this.val = data.val;
                }
            }
        }
        get val() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set val(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            val?: number;
        }): Int {
            const message = new Int({});
            if (data.val != null) {
                message.val = data.val;
            }
            return message;
        }
        toObject() {
            const data: {
                val?: number;
            } = {};
            if (this.val != null) {
                data.val = this.val;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.val != 0)
                writer.writeInt32(1, this.val);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Int {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Int();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.val = reader.readInt32();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Int {
            return Int.deserialize(bytes);
        }
    }
    export class Void extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {}) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") { }
        }
        static fromObject(data: {}): Void {
            const message = new Void({});
            return message;
        }
        toObject() {
            const data: {} = {};
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Void {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Void();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Void {
            return Void.deserialize(bytes);
        }
    }
    export class Arr extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            arr?: number[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("arr" in data && data.arr != undefined) {
                    this.arr = data.arr;
                }
            }
        }
        get arr() {
            return pb_1.Message.getFieldWithDefault(this, 1, []) as number[];
        }
        set arr(value: number[]) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            arr?: number[];
        }): Arr {
            const message = new Arr({});
            if (data.arr != null) {
                message.arr = data.arr;
            }
            return message;
        }
        toObject() {
            const data: {
                arr?: number[];
            } = {};
            if (this.arr != null) {
                data.arr = this.arr;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.arr.length)
                writer.writePackedInt32(1, this.arr);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Arr {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Arr();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.arr = reader.readPackedInt32();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Arr {
            return Arr.deserialize(bytes);
        }
    }
    export class Obj extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            payload?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("payload" in data && data.payload != undefined) {
                    this.payload = data.payload;
                }
            }
        }
        get payload() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set payload(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            payload?: string;
        }): Obj {
            const message = new Obj({});
            if (data.payload != null) {
                message.payload = data.payload;
            }
            return message;
        }
        toObject() {
            const data: {
                payload?: string;
            } = {};
            if (this.payload != null) {
                data.payload = this.payload;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.payload.length)
                writer.writeString(1, this.payload);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Obj {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Obj();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.payload = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Obj {
            return Obj.deserialize(bytes);
        }
    }
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcStreamServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
        (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    }
    interface GrpWritableServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    interface GrpcPromiseServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
        (message: P, options?: grpc_1.CallOptions): Promise<R>;
    }
    export abstract class UnimplementedTestService {
        static definition = {
            Test: {
                path: "/test.Test/Test",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: Int) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => Int.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Int) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Int.deserialize(new Uint8Array(bytes))
            },
            Test1: {
                path: "/test.Test/Test1",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: Int) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => Int.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Void) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Void.deserialize(new Uint8Array(bytes))
            },
            EmitEvent: {
                path: "/test.Test/EmitEvent",
                requestStream: false,
                responseStream: true,
                requestSerialize: (message: Obj) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => Obj.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Arr) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Arr.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract Test(call: grpc_1.ServerUnaryCall<Int, Int>, callback: grpc_1.sendUnaryData<Int>): void;
        abstract Test1(call: grpc_1.ServerUnaryCall<Int, Void>, callback: grpc_1.sendUnaryData<Void>): void;
        abstract EmitEvent(call: grpc_1.ServerWritableStream<Obj, Arr>): void;
    }
    export class TestClient extends grpc_1.makeGenericClientConstructor(UnimplementedTestService.definition, "Test", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        Test: GrpcUnaryServiceInterface<Int, Int> = (message: Int, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Int>, options?: grpc_1.CallOptions | grpc_1.requestCallback<Int>, callback?: grpc_1.requestCallback<Int>): grpc_1.ClientUnaryCall => {
            return super.Test(message, metadata, options, callback);
        };
        Test1: GrpcUnaryServiceInterface<Int, Void> = (message: Int, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Void>, options?: grpc_1.CallOptions | grpc_1.requestCallback<Void>, callback?: grpc_1.requestCallback<Void>): grpc_1.ClientUnaryCall => {
            return super.Test1(message, metadata, options, callback);
        };
        EmitEvent: GrpcStreamServiceInterface<Obj, Arr> = (message: Obj, metadata?: grpc_1.Metadata | grpc_1.CallOptions, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<Arr> => {
            return super.EmitEvent(message, metadata, options);
        };
    }
}
