import { ABILITY_NAME } from "./Ability/AbilityRegistry"

export class AbilityTag extends Set<ABILITY_NAME>{}

export namespace AbilityTags {
	export const CONSTRUCTION_TOOLS = new AbilityTag([
		ABILITY_NAME.GO_START_ON_THREE_HOUSE,
		ABILITY_NAME.UPGRADE_LAND_AND_MULTIPLIER_ON_BUILD,
	])
	export const ON_ANY_BUILD_ABILITY = new AbilityTag([
		ABILITY_NAME.GO_START_ON_THREE_HOUSE,
		ABILITY_NAME.UPGRADE_LAND_AND_MULTIPLIER_ON_BUILD,
		ABILITY_NAME.LINE_BUYOUT_ON_BUILD,
		ABILITY_NAME.LINE_LANDMARK_ON_BUILD,
	])
	export const GO_STARTS = new AbilityTag([ABILITY_NAME.GO_START_ON_THREE_HOUSE])
	export const TRAVELS = new AbilityTag([
		ABILITY_NAME.TRAVEL_ON_ENEMY_LAND,
		ABILITY_NAME.FREE_AND_TRAVEL_ON_ENEMY_LAND,
		ABILITY_NAME.TRAVEL_ON_TRIPLE_DOUBLE,
		ABILITY_NAME.FREE_AND_TRAVEL_ON_ENEMY_AND_MY_LAND,
	])
	export const LANDMARK_PULLS = new AbilityTag([
		ABILITY_NAME.LINE_PULL_ON_ARRIVE_AND_BUILD_LANDMARK,
		ABILITY_NAME.RANGE_PULL_ON_ARRIVE_LANDMARK,
	])
	export const GUIDEBOOK = new AbilityTag([
		ABILITY_NAME.THROW_TO_LANDMARK_AND_DONATE_ON_ENEMY_ARRIVE_TO_ME,
		ABILITY_NAME.THROW_TO_LANDMARK_ON_ENEMY_ARRIVE_TO_ME,
		ABILITY_NAME.THROW_TO_LANDMARK_WITH_MULTIPLIER
	])

	export const TRIPLE_DOUBLE_OVERRIDER = new AbilityTag([
		ABILITY_NAME.TRAVEL_ON_TRIPLE_DOUBLE,
		// ABILITY_NAME.INSTANT_ESCAPE_ISLAND,
		ABILITY_NAME.LINE_MOVE_ON_TRIPLE_DOUBLE,
	])

	export const ANGEL = new AbilityTag([ABILITY_NAME.ANGEL_CARD])
}
