
export enum EFFECT_SOURCE {
	ENEMY,
	ALLY,
	OBSTACLE,
	ITEM,
}
export enum EFFECT_TYPE {
	NORMAL = 0,
	SHIELD = 1,
	ABILITY_CHANGE = 2,
	ONHIT = 3,
	ONDAMAGE = 4,
	TICK = 5,
	ON_HP_BELOW_THRESHOLD = 6,
}
export enum EFFECT_TIMING {
	TURN_START,
	TURN_END,
	BEFORE_SKILL,
	BEFORE_OBS,
}
export const SHIELD_EFFECT_TIMING = EFFECT_TIMING.BEFORE_SKILL
export const ABILITY_CHANGE_EFFECT_TIMING = EFFECT_TIMING.TURN_START
export const TICK_EFFECT_TIMING = EFFECT_TIMING.TURN_END
export const ONHIT_EFFECT_TIMING = EFFECT_TIMING.BEFORE_OBS
export const ONHPBELOWTHRESHOLD_EFFECT_TIMING = EFFECT_TIMING.BEFORE_OBS
export const ON_DAMAGE_EFFECT_TIMING = EFFECT_TIMING.BEFORE_OBS

export enum EFFECT{
	SLOW= 0,
	SPEED= 1,
	GROUNGING= 2,
	SILENT= 3,
	SHIELD= 4,
	POISON= 5,
	RADI= 6,
	ANNUITY= 7,
	SLAVE= 8,
	BACKDICE= 9,
	DOUBLEDICE= 10,
	BLIND= 11,
	IGNITE= 12,
	INVISIBILITY= 13,
	PRIVATE_LOAN= 14,
	ANNUITY_LOTTERY= 15,
	CURSE= 16,
	FARSIGHT=17,
	ROOT = 18,


	REAPER_Q_SHIELD=31,
	REAPER_ULT_SHIELD=32,

	GHOST_ULT_DAMAGE=33,
	GHOST_ULT_WEAKEN=34,

	ELEPHANT_W_SIGN=35,
	ELEPHANT_ULT_SHIELD=36,
	ELEPHANT_ULT_RESISTANCE=37,
	ELEPHANT_PASSIVE_RESISTANCE=38,

	SNIPER_ULT_SHIELD=39,

	MAGICIAN_W_SHIELD=40,
	MAGICIAN_W_BURN=41,
	MAGICIAN_W=51,

	KRAKEN_W_SHIELD=42,

	BIRD_ULT_SHIELD=43,
	BIRD_ULT_ABILITY=44,
	BIRD_ULT_BURN=45,
	
	DINOSAUR_W=46,
	
	TREE_WITHER=47,
	TREE_ULT=48,
	TREE_Q_SHIELD=49,
	BIRD_W=50,
	HACKER_ULT=51,
	HACKER_ULT_ENEMY=52,
	MAGIC_CASTLE_ADAMAGE=69,

	ITEM_SHIELDSWORD=70,
	ITEM_FRUIT,
	ITEM_POWER_OF_NATURE,
	ITEM_POWER_OF_MOTHER_NATURE1,
	ITEM_POWER_OF_MOTHER_NATURE2,
	ITEM_CARD_OF_DECEPTION,
	ITEM_ANCIENT_SPEAR2,
	ITEM_ANCIENT_SPEAR1,
	ITEM_SPEAR2,
	ITEM_SPEAR1,
	ITEM_CROSSBOW1,
	ITEM_CROSSBOW2,
	ITEM_DIAMOND_ARMOR,
	ITEM_BOOTS_OF_ENDURANCE,
	ITEM_INVISIBILITY_CLOAK,
	ITEM_DAGGER,
	ITEM_STAFF_OF_JUDGEMENT,
	ITEM_FLAIL_OF_JUDGEMENT,
	ITEM_FLAIL_OF_JUDGEMENT_RANGE,
	ITEM_ABILITY_POWER_OF_MOTHER_NATURE,
	ITEM_ABILITY_SHIELDSWORD_SHIELD,
	ITEM_ABILITY_SHIELDSWORD_ABSORB,
}