export enum BEFORE_OBS {
    INITIALIZE=0,
	WAITING_DICE,
	THROW_DICE,
	STUN,
	AI_THROW_DICE
}
export enum BEFORE_SKILL {
	ARRICE_SQUARE = 10,
	PENDING_OBSTACLE,
	PENDING_ACTION
}
export enum SKILL {
	SILENT = 20,
	AI_SKILL,
	WAITING_SKILL,
	WAITING_TARGET,
	WAITING_LOCATION,
	WAITING_AREA_TARGET
}
export const GAMEOVER=999